### ISSUE TITLE
Compilation fails 

### ISSUE THREAD

**Issue by seifreed** [fxb-cocacoding/yara-signator#1]
I'm trying to build yara signator and I'm getting the following error:

```
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project yara-signator: Compilation failure
[ERROR] /home/seifreed/yara-signator/src/main/java/mongodb/MongoHandler.java:[15,22] package javax.xml.bind does not exist
```

Could you please help me?

**Comment by fxb-cocacoding** [comment]
Hey,

thanks for the ticket. I just update this issue for everyone since you already contacted me.

Currently only Java 8 is supported as some parts of the projects rely on dependencies which were deprecated until Java 10 and then removed in Java 11.

I will not fix this in this version since I am working on a new version without these dependencies.
